const fs = require('fs');
const path = require('path');
const file = path.join(__dirname, 'index.html');
let html = fs.readFileSync(file, 'utf8');
html = html.replace('<label>ایمیل</label><input id="signupEmail" type="email" placeholder="ایمیل شما">','<label>ایمیل <span style="font-size:11px;color:#667085">(اختیاری)</span></label><input id="signupEmail" type="email" placeholder="ایمیل شما (اختیاری)">');
const old = /\$\('signupBtn'\)\.onclick=async\(\)=>\{.*?\};s\.auth\.onAuthStateChange/s;
const replacement = `$('signupBtn').onclick=async()=>{const name=$('signupName').value.trim(),rawPhone=$('signupPhone').value.trim(),phone=normalizePhone(rawPhone),email=$('signupEmail').value.trim(),password=$('signupPassword').value,password2=$('signupPassword2').value;if(!name||!phone||!password)return showMsg('نام، شماره موبایل و رمز عبور الزامی است.');if(password.length<6)return showMsg('رمز عبور باید حداقل ۶ کاراکتر باشد.');if(password!==password2)return showMsg('تکرار رمز عبور صحیح نیست.');const{data:existing}=await s.rpc('lookup_email_by_phone',{p_phone:phone});if(existing)return showMsg('این شماره موبایل قبلاً ثبت شده است.');let data,error;if(email){({data,error}=await s.auth.signUp({email,password,options:{data:{full_name:name,phone},emailRedirectTo:location.origin+'/'}}))}else{({data,error}=await s.auth.signUp({phone,password,options:{data:{full_name:name,phone}}}))}if(error)return showMsg(error.message);if(data.user){if(data.session){showMsg('ثبت‌نام با موفقیت انجام شد.',true);setTimeout(()=>{location.href=location.origin+'/'},700)}else{setTimeout(()=>{location.href=location.origin+'/'},700)}}};s.auth.onAuthStateChange`;
if(!old.test(html)) throw new Error('signup handler not found');
html = html.replace(old, replacement);
fs.writeFileSync(file, html);
console.log('Build completed successfully');
