(function(){
const SB_URL='https://aserkyiwwyggtixckjsv.supabase.co',SB_KEY='sb_publishable_7THOazCrwgQGvRPGC8grgA_6J1E_9HX',db=supabase.createClient(SB_URL,SB_KEY),$=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const money=n=>Number(n||0).toLocaleString('fa-IR'),dateOnly=d=>d?new Date(d).toLocaleDateString('fa-IR'):'—';let canManage=false;
const notice=t=>{const n=$('commissionNotice');if(n){n.textContent=t;setTimeout(()=>n.textContent='',4500)}};
async function access(){const{data:{session}}=await db.auth.getSession();if(!session)return false;const role=sessionStorage.getItem('activeAdminRole')||'finance_manager';const[v,m]=await Promise.all([db.rpc('has_admin_role_permission',{p_role:role,p_permission:'finance.view'}),db.rpc('has_admin_role_permission',{p_role:role,p_permission:'finance.manage'})]);if(v.error||v.data!==true)return false;canManage=!m.error&&m.data===true;return true}
function inject(){if($('commissionRules'))return;const notice=$('notice');if(!notice)return;const w=document.createElement('div');w.id='commissionRules';w.innerHTML=`<section class="card"><div class="toolbar"><h2 style="margin-left:auto">⚖️ قوانین سهم مشاور</h2><button class="btn gray" id="refreshCommissionRules">🔄 بروزرسانی</button></div><div id="commissionNotice" class="notice"></div><p class="muted">درصد سهم مشاور برای محاسبه خودکار تسویه‌های مالی. درصد بین ۰ تا ۱۰۰ است.</p><div class="fields"><div><label>مشاور<select id="commissionConsultant"></select></label><label>درصد سهم مشاور<input id="commissionPercent" type="number" min="0" max="100" step="0.01" placeholder="مثلاً 60"></label></div><div><label>شروع اعتبار<input id="commissionFrom" type="date"></label><label>پایان اعتبار (اختیاری)<input id="commissionTo" type="date"></label><button class="btn green" id="saveCommissionRule">💾 ثبت قانون سهم</button></div></div><div class="table"><table><thead><tr><th>مشاور</th><th>درصد سهم</th><th>شروع</th><th>پایان</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody id="commissionRulesBody"></tbody></table></div></section>`;notice.insertAdjacentElement('afterend',w);$('refreshCommissionRules').onclick=load;$('saveCommissionRule').onclick=save}
async function loadConsultants(){const r=await db.from('consultants').select('id,name,is_active').order('name');if(r.error)return notice(r.error.message);$('commissionConsultant').innerHTML=(r.data||[]).filter(x=>x.is_active).map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('')||'<option value="">مشاور فعالی وجود ندارد</option>'}
async function loadRules(){const r=await db.from('consultant_commission_rules').select('id,consultant_id,commission_percent,effective_from,effective_to,is_active,created_at,consultants(name)').order('created_at',{ascending:false});if(r.error)return $('commissionRulesBody').innerHTML=`<tr><td colspan="6">${esc(r.error.message)}</td></tr>`;const rows=r.data||[];$('commissionRulesBody').innerHTML=rows.length?rows.map(x=>`<tr><td>${esc(x.consultants?.name||'—')}</td><td>${money(x.commission_percent)}٪</td><td>${dateOnly(x.effective_from)}</td><td>${dateOnly(x.effective_to)}</td><td>${x.is_active?'<span class="badge">فعال</span>':'غیرفعال'}</td><td>${canManage?(x.is_active?`<button class="btn red" onclick="window.disableCommissionRule('${x.id}')">غیرفعال</button>`:'—'):'—'}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">هنوز قانون سهمی ثبت نشده است.</td></tr>'}
async function audit(action,id,beforeData,afterData){const r=await db.rpc('record_finance_audit',{p_action:action,p_entity_type:'consultant_commission_rule',p_entity_id:id,p_before:beforeData||null,p_after:afterData||null,p_note:'مدیریت قانون سهم مشاور'});if(r.error)console.warn('audit failed',r.error.message)}
async function save(){if(!canManage)return notice('این نقش اجازه مدیریت قوانین سهم را ندارد.');const consultant_id=$('commissionConsultant').value,percent=Number($('commissionPercent').value),from=$('commissionFrom').value,to=$('commissionTo').value||null;if(!consultant_id||!Number.isFinite(percent)||percent<0||percent>100||!from)return notice('مشاور، درصد و تاریخ شروع الزامی است.');if(to&&to<from)return notice('تاریخ پایان نمی‌تواند قبل از شروع باشد.');const q=await db.from('consultant_commission_rules').select('id,effective_from,effective_to').eq('consultant_id',consultant_id).eq('is_active',true);if(q.error)return notice(q.error.message);const overlaps=(q.data||[]).some(x=>{const a=x.effective_from.slice(0,10),b=x.effective_to?x.effective_to.slice(0,10):'9999-12-31',c=from,d=to||'9999-12-31';return c<=b&&a<=d});if(overlaps)return notice('برای این مشاور در این بازه، یک قانون فعال دیگر وجود دارد.');const{data:{user}}=await db.auth.getUser();const ins=await db.from('consultant_commission_rules').insert({consultant_id,commission_percent:percent,effective_from:from+'T00:00:00',effective_to:to?to+'T23:59:59':null,is_active:true,created_by:user?.id}).select('id,commission_percent,effective_from,effective_to,is_active').single();if(ins.error)return notice(ins.error.message);await audit('commission_rule_created',ins.data.id,null,ins.data);$('commissionPercent').value='';$('commissionFrom').value='';$('commissionTo').value='';await loadRules();notice('قانون سهم مشاور با موفقیت ثبت شد.')}
window.disableCommissionRule=async function(id){if(!canManage)return;if(!confirm('این قانون غیرفعال شود؟'))return;const old=await db.from('consultant_commission_rules').select('*').eq('id',id).single();if(old.error)return notice(old.error.message);const r=await db.from('consultant_commission_rules').update({is_active:false,effective_to:new Date().toISOString()}).eq('id',id).eq('is_active',true);if(r.error)return notice(r.error.message);const after={...old.data,is_active:false};await audit('commission_rule_disabled',id,old.data,after);await loadRules();notice('قانون غیرفعال شد.')};
async function load(){await loadConsultants();await loadRules();if(!canManage)$('saveCommissionRule').style.display='none'}
async function start(){if(location.pathname!='/admin-v5.html'||!(await access()))return;inject();await load()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();})();