import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AlertCircle, CalendarDays, CheckCircle2, Clock3, CreditCard, LoaderCircle, LogOut, RefreshCw, ShieldCheck, Stethoscope, Users, WalletCards } from 'lucide-react';
import { supabase, signOutUser } from './lib/supabase';
import './styles.css';

const money = (v) => `${new Intl.NumberFormat('fa-IR').format(Number(v || 0))} ریال`;
const dateTime = (v) => v ? new Intl.DateTimeFormat('fa-IR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(v)) : '—';
const appointmentLabels = { PENDING_PAYMENT:'در انتظار پرداخت', HELD:'رزرو موقت', CONFIRMED:'قطعی شده', CANCELLED:'لغو شده', COMPLETED:'انجام شده', EXPIRED:'منقضی شده' };
const paymentLabels = { PENDING:'در انتظار پرداخت', INITIATED:'در انتظار پرداخت', VERIFIED:'تأیید شده', PAID:'پرداخت موفق', FAILED:'ناموفق', CANCELLED:'لغو شده' };

function Stat({ icon: Icon, title, value, text }) { return <article className="account-card admin-stat"><div className="form-icon"><Icon size={22}/></div><span>{title}</span><strong>{value}</strong><small>{text}</small></article>; }

function Dashboard() {
 const [session,setSession]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [appointments,setAppointments]=useState([]),[payments,setPayments]=useState([]),[psychologists,setPsychologists]=useState([]),[slots,setSlots]=useState([]),[section,setSection]=useState('overview'),[busy,setBusy]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const {data:{session:s}}=await supabase.auth.getSession();if(!s)throw new Error('برای ورود به داشبورد باید با حساب ادمین وارد شوید.');setSession(s);const [a,p,psy,sl]=await Promise.all([supabase.from('appointments').select('id,status,gross_amount,currency,created_at,confirmed_at,client_id,slot_id,psychologist_id,appointment_slots:slot_id(starts_at,ends_at,duration_minutes),profiles:client_id(first_name,last_name,display_name),psychologists:psychologist_id(professional_title)').order('created_at',{ascending:false}).limit(200),supabase.from('payments').select('id,appointment_id,amount,currency,status,gateway,reference_number,paid_at,created_at').order('created_at',{ascending:false}).limit(200),supabase.from('psychologists').select('id,professional_title,years_experience,status,phone_price,phone_duration,created_at').order('created_at',{ascending:false}),supabase.from('appointment_slots').select('id,starts_at,ends_at,duration_minutes,price,status,psychologist_id,psychologists:psychologist_id(professional_title)').order('starts_at',{ascending:true}).limit(200)]);for(const r of [a,p,psy,sl])if(r.error)throw r.error;setAppointments(a.data||[]);setPayments(p.data||[]);setPsychologists(psy.data||[]);setSlots(sl.data||[])}catch(e){setError(e?.message||'دریافت داشبورد انجام نشد.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const paymentMap=useMemo(()=>new Map(payments.map(p=>[p.appointment_id,p])),[payments]);
 const stats=useMemo(()=>{const paid=payments.filter(p=>['PAID','VERIFIED'].includes(p.status));return {appointments:appointments.length,pendingCash:payments.filter(p=>p.gateway==='cash'&&p.status==='PENDING'&&['PENDING_PAYMENT','HELD'].includes(appointments.find(a=>a.id===p.appointment_id)?.status)).length,confirmed:appointments.filter(a=>a.status==='CONFIRMED').length,revenue:paid.reduce((s,p)=>s+Number(p.amount||0),0),psychologists:psychologists.filter(p=>p.status==='APPROVED').length,available:slots.filter(s=>s.status==='AVAILABLE').length}} , [appointments,payments,psychologists,slots]);
 const confirmCash=async(id)=>{setBusy(id);setError('');try{const {error:e}=await supabase.rpc('confirm_cash_payment',{p_appointment_id:id});if(e)throw e;setNotice('پرداخت نقدی تأیید و نوبت قطعی شد.');await load()}catch(e){setError(e?.message||'تأیید انجام نشد.')}finally{setBusy('')}};
 const nav=[['overview','داشبورد',WalletCards],['appointments','نوبت‌ها',CalendarDays],['payments','پرداخت‌ها',CreditCard],['cash','پرداخت نقدی',CheckCircle2],['psychologists','مشاوران',Stethoscope],['slots','نوبت‌های آزاد',Clock3],['users','کاربران',Users]];
 if(loading)return <main className="request-section"><div className="container"><div className="success-box"><LoaderCircle className="spin" size={34}/><p>در حال بارگذاری داشبورد مدیریت...</p></div></div></main>;
 if(!session)return <main className="request-section"><div className="container"><div className="success-box"><ShieldCheck size={42}/><h1>دسترسی مدیریت</h1><p>این بخش فقط برای حساب دارای نقش ADMIN است.</p><a className="primary-button" href="/">بازگشت</a></div></div></main>;
 const pendingCash=payments.filter(p=>p.gateway==='cash'&&p.status==='PENDING'&&['PENDING_PAYMENT','HELD'].includes(appointments.find(a=>a.id===p.appointment_id)?.status));
 const appointmentRows=appointments.slice(0,50);
 return <main className="admin-dashboard"><div className="admin-shell"><aside className="admin-sidebar"><div className="admin-brand"><ShieldCheck size={24}/><div><strong>مدیریت مرکز</strong><small>مرکز مشاوره تلفنی روان</small></div></div>{nav.map(([key,label,Icon])=><button key={key} className={section===key?'admin-nav active':'admin-nav'} onClick={()=>setSection(key)}><Icon size={18}/>{label}</button>)}<button className="admin-nav" onClick={async()=>{await signOutUser();setSession(null)}}><LogOut size={18}/>خروج</button></aside><section className="admin-content"><header className="admin-header"><div><span className="eyebrow">پنل مدیریت</span><h1>{nav.find(n=>n[0]===section)?.[1]}</h1></div><button className="secondary-button" onClick={load}><RefreshCw size={17}/> به‌روزرسانی</button></header>{notice&&<div className="success-box"><CheckCircle2 size={20}/><p>{notice}</p></div>}{error&&<div className="auth-error"><AlertCircle size={18}/>{error}</div>}
 {section==='overview'&&<><div className="admin-stats"><Stat icon={CalendarDays} title="کل نوبت‌ها" value={stats.appointments} text="ثبت‌شده"/><Stat icon={CheckCircle2} title="نوبت قطعی" value={stats.confirmed} text="تأیید شده"/><Stat icon={WalletCards} title="درآمد وصول‌شده" value={money(stats.revenue)} text="پرداخت‌های موفق"/><Stat icon={CreditCard} title="پرداخت نقدی" value={stats.pendingCash} text="در انتظار تأیید"/><Stat icon={Stethoscope} title="مشاوران فعال" value={stats.psychologists} text="تأیید شده"/><Stat icon={Clock3} title="نوبت آزاد" value={stats.available} text="قابل رزرو"/></div><section className="admin-panel"><h2>آخرین نوبت‌ها</h2><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>کاربر</th><th>زمان</th><th>وضعیت</th><th>مبلغ</th></tr></thead><tbody>{appointmentRows.slice(0,10).map(a=><tr key={a.id}><td>{a.profiles?.display_name||[a.profiles?.first_name,a.profiles?.last_name].filter(Boolean).join(' ')||'کاربر'}</td><td>{dateTime(a.appointment_slots?.starts_at)}</td><td>{appointmentLabels[a.status]||a.status}</td><td>{money(a.gross_amount)}</td></tr>)}</tbody></table></div></section></>}
 {section==='appointments'&&<DataTable title="مدیریت نوبت‌ها"><table className="admin-table"><thead><tr><th>کاربر</th><th>مشاور</th><th>زمان</th><th>وضعیت</th><th>مبلغ</th></tr></thead><tbody>{appointments.map(a=><tr key={a.id}><td>{a.profiles?.display_name||[a.profiles?.first_name,a.profiles?.last_name].filter(Boolean).join(' ')||'کاربر'}</td><td>{a.psychologists?.professional_title||'—'}</td><td>{dateTime(a.appointment_slots?.starts_at)}</td><td>{appointmentLabels[a.status]||a.status}</td><td>{money(a.gross_amount)}</td></tr>)}</tbody></table></DataTable>}
 {section==='payments'&&<DataTable title="تاریخچه پرداخت‌ها"><table className="admin-table"><thead><tr><th>نوبت</th><th>روش</th><th>وضعیت</th><th>مبلغ</th><th>پیگیری</th></tr></thead><tbody>{payments.map(p=><tr key={p.id}><td><code>{p.appointment_id}</code></td><td>{p.gateway||'—'}</td><td>{paymentLabels[p.status]||p.status}</td><td>{money(p.amount)}</td><td>{p.reference_number||'—'}</td></tr>)}</tbody></table></DataTable>}
 {section==='cash'&&<DataTable title={`درخواست‌های نقدی (${pendingCash.length})`}><table className="admin-table"><thead><tr><th>کاربر</th><th>زمان</th><th>مبلغ</th><th>عملیات</th></tr></thead><tbody>{pendingCash.map(p=>{const a=appointments.find(x=>x.id===p.appointment_id);return <tr key={p.id}><td>{a?.profiles?.display_name||[a?.profiles?.first_name,a?.profiles?.last_name].filter(Boolean).join(' ')||'کاربر'}</td><td>{dateTime(a?.appointment_slots?.starts_at)}</td><td>{money(p.amount)}</td><td><button className="primary-button" disabled={busy===p.appointment_id} onClick={()=>confirmCash(p.appointment_id)}>{busy===p.appointment_id?<LoaderCircle className="spin" size={17}/>:<CheckCircle2 size={17}/>} تأیید دریافت وجه</button></td></tr>})}</tbody></table>{!pendingCash.length&&<p className="empty-table">درخواست نقدی در انتظار تأیید وجود ندارد.</p>}</DataTable>}
 {section==='psychologists'&&<DataTable title="مشاوران"><table className="admin-table"><thead><tr><th>عنوان حرفه‌ای</th><th>سابقه</th><th>قیمت تلفنی</th><th>وضعیت</th></tr></thead><tbody>{psychologists.map(p=><tr key={p.id}><td>{p.professional_title}</td><td>{p.years_experience||0} سال</td><td>{money(p.phone_price)}</td><td>{p.status}</td></tr>)}</tbody></table></DataTable>}
 {section==='slots'&&<DataTable title="نوبت‌ها"><table className="admin-table"><thead><tr><th>زمان</th><th>مشاور</th><th>مدت</th><th>قیمت</th><th>وضعیت</th></tr></thead><tbody>{slots.map(s=><tr key={s.id}><td>{dateTime(s.starts_at)}</td><td>{s.psychologists?.professional_title||'—'}</td><td>{s.duration_minutes} دقیقه</td><td>{money(s.price)}</td><td>{s.status}</td></tr>)}</tbody></table></DataTable>}
 {section==='users'&&<DataTable title="کاربران"><p className="admin-note">اطلاعات کاربران از جدول پروفایل‌ها خوانده می‌شود؛ اطلاعات حساس احراز هویت در این داشبورد نمایش داده نمی‌شود.</p></DataTable>}
 </section></div></main>;
}
function DataTable({title,children}){return <section className="admin-panel"><h2>{title}</h2>{children}</section>}
createRoot(document.getElementById('root')).render(<Dashboard/>);
